---
example.org:
  format: haproxy
  server:
    - haproxy1
    - haproxy2
---
example.cz:
  format: haproxy
  server:
    - haproxy1
    - haproxy2
---
example.org:
  format: apache
  server:
    - webserver
---
web.example.org:
  format: apache
  server:
    - webserver
